/* THIS FILE IS AUTOMATICALLY GENERATED */
#ifndef EXAMPLE_H
#define EXAMPLE_H

#include <stdint.h>
#include <msgbus/type_definition.h>


/** Example type */
typedef struct {
    char name[51];  /**< sender name (max 50 characters) */
    int32_t data;
} example_t;

/* messagebus type definitions */
extern const messagebus_type_definition_t example_type;

#endif /* EXAMPLE_H */
