/* THIS FILE IS AUTOMATICALLY GENERATED */
#include <msgbus/type_definition.h>
#include "example.h"

static const messagebus_type_entry_t example_entries[] = {
    {
        .name = "name",
        .is_base_type = 1,
        .is_array = 0,
        .is_dynamic_array = 0,
        .array_len = 0,
        .dynamic_array_len_struct_offset = 0,
        .struct_offset = offsetof(example_t, name),
        .base_type = MESSAGEBUS_TYPE_STRING,
        .size = sizeof(char[51]),
    },
    {
        .name = "data",
        .is_base_type = 1,
        .is_array = 0,
        .is_dynamic_array = 0,
        .array_len = 0,
        .dynamic_array_len_struct_offset = 0,
        .struct_offset = offsetof(example_t, data),
        .base_type = MESSAGEBUS_TYPE_INT32,
        .size = sizeof(int32_t),
    },
};

const messagebus_type_definition_t example_type = {
    .nb_elements = 2,
    .elements = example_entries,
    .struct_size = sizeof(example_t),
};

